build error Fedora 19 alpha
On Fedora 19 alpha the following compile error occurs:
gcc .....   -c -o lldp_8021qaz_cmds.o lldp_8021qaz_cmds.c
lldp_8021qaz_cmds.c: In function ‘_set_arg_tsa’:
lldp_8021qaz_cmds.c:848:24: error: argument to ‘sizeof’ in ‘memset’ call is the same expression as the destination; did you mean to provide an explicit length? [-Werror=sizeof-pointer-memaccess]
memset(tsa, 0, sizeof(tsa));
                      ^
cc1: all warnings being treated as errors
make: *** [lldp_8021qaz_cmds.o] Error 1

It looks like the length is incorrect. The variable tsa points
to an octet array, so the length should be more than a
pointer size.

Signed-off-by: Thomas Richter <tmricht@linux.vnet.ibm.com>
Signed-off-by: John Fastabend <john.r.fastabend@intel.com>